volumes:
  mysql_data:
<<<<<<< HEAD
  redis_data:      
=======
  redis_data:
>>>>>>> upstream/main

services:
  mysql:
    image: mysql:8
        target: 6379
    volumes:
      - redis_data:/data

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - published: ${DEMO_MAILHOG_HTTP_PORT:-8025}
        target: 8025
