volumes:
  mysql_data:
  redis_data:      

services:
  mysql:
    image: mysql:8
    ports: 
      - ${DEMO_MYSQL_PORT:-3306}:3306
    volumes:
      - mysql_data:/var/lib/mysql      
    environment:
      MYSQL_USER: demo
      MYSQL_PASSWORD: 3x4mpl3p455w0rd
      MYSQL_DATABASE: demo_development
      MYSQL_ROOT_PASSWORD: 3x4mpl3p455w0rd
  redis:
    image: redis:6-alpine
    ports:
      - published: 6379
        target: 6379     
    volumes:
      - redis_data:/data
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - published: ${DEMO_MAILHOG_HTTP_PORT:-8025}
        target: 8025           